local constants = require("printer.constants")

function init(self)
	msg.post(constants.PRINTER, constants.PRINT, { text = "Hello, Defold World!{n}{n}"..
	"- {n}"..
	"You can insert line breaks using [n]{n}"..
	"You can {shake}shake text{/} using [shake]{n}"..
	"And even make text {slow_appear}slowly appear!{/} with [slow_appear]{n}"..
	"Define your own styles like this:{n}"..
	"shake = [{n}color = #f22222,{n} speed = 0.1,{n} appear = 0,{n}shake_on_write = 4,{n}sound = shake_sound{n}]"})
end